// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_1001_2021_Basic_Web_App.Data.Context;

namespace WEB_1001_2021_Basic_Web_App.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20210712214653_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("WEB_1001_2021_Basic_Web_App.Data.Color", b =>
                {
                    b.Property<string>("RGB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductSKU")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortCode")
                        .HasColumnType("TEXT");

                    b.HasKey("RGB");

                    b.HasIndex("ProductSKU");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("WEB_1001_2021_Basic_Web_App.Data.Customer", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WEB_1001_2021_Basic_Web_App.Data.Material", b =>
                {
                    b.Property<string>("ShortCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductSKU")
                        .HasColumnType("TEXT");

                    b.HasKey("ShortCode");

                    b.HasIndex("ProductSKU");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("WEB_1001_2021_Basic_Web_App.Data.Media", b =>
                {
                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorRGB")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialShortCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaDescriptor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductSKU")
                        .HasColumnType("TEXT");

                    b.HasKey("FilePath");

                    b.HasIndex("ColorRGB");

                    b.HasIndex("MaterialShortCode");

                    b.HasIndex("ProductSKU");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("WEB_1001_2021_Basic_Web_App.Data.Product", b =>
                {
                    b.Property<string>("SKU")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimensions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubCategory")
                        .HasColumnType("TEXT");

                    b.HasKey("SKU");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WEB_1001_2021_Basic_Web_App.Data.Color", b =>
                {
                    b.HasOne("WEB_1001_2021_Basic_Web_App.Data.Product", null)
                        .WithMany("Colors")
                        .HasForeignKey("ProductSKU");
                });

            modelBuilder.Entity("WEB_1001_2021_Basic_Web_App.Data.Material", b =>
                {
                    b.HasOne("WEB_1001_2021_Basic_Web_App.Data.Product", null)
                        .WithMany("Materials")
                        .HasForeignKey("ProductSKU");
                });

            modelBuilder.Entity("WEB_1001_2021_Basic_Web_App.Data.Media", b =>
                {
                    b.HasOne("WEB_1001_2021_Basic_Web_App.Data.Color", null)
                        .WithMany("Media")
                        .HasForeignKey("ColorRGB");

                    b.HasOne("WEB_1001_2021_Basic_Web_App.Data.Material", null)
                        .WithMany("Media")
                        .HasForeignKey("MaterialShortCode");

                    b.HasOne("WEB_1001_2021_Basic_Web_App.Data.Product", null)
                        .WithMany("Media")
                        .HasForeignKey("ProductSKU");
                });

            modelBuilder.Entity("WEB_1001_2021_Basic_Web_App.Data.Color", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("WEB_1001_2021_Basic_Web_App.Data.Material", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("WEB_1001_2021_Basic_Web_App.Data.Product", b =>
                {
                    b.Navigation("Colors");

                    b.Navigation("Materials");

                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
